# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_username: test
  admin_password: test
  secret_key_base: 44858f2bf78ad0dd05f1d47730fe16681f6a16d0fd6aff4ecfe2eeeeb323e7675d212775a0e42ca4b0e26e96a6ffe116738e14330a625e65708fc23786426cae

test:
  admin_username: test
  admin_password: test
  secret_key_base: 5ec511733be77dc0b45edec7b8d130c2275921bf69cac6e8463352f274014c543659ec2f888d1e42a77c4a35744619f3e21476873dcc0e20f9acc4664afd0f7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_username: <%= ENV["ADMIN_USERNAME"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
